name: Execute Auto Merge Branches

on:
  push:
    branches:
      - prod
      - staging
    paths-ignore:
      - "generated/**/*"
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch name"
        required: false

jobs:
  # Figure out what branch triggered this
  determine-branch:
    runs-on: ubuntu-latest
    outputs:
      branch: ${{ steps.determine-branch.outputs.branch }}
    steps:
      - name: Ensure not triggered by GitHub Actions bot
        if: github.actor == 'github-actions[bot]'
        run: echo "Skipping workflow as it was triggered by github-actions[bot]"

      - name: Determine branch name that triggered this action
        id: determine-branch
        run: |
          echo "Branch that triggered the action: ${{ github.ref_name }}"
          echo "::set-output name=branch::${{ github.ref_name }}"

  call-auto-merge:
    needs: determine-branch
    if: ${{ needs.determine-branch.outputs.branch && github.actor != 'github-actions[bot]' }}
    uses: mobilefirstdev/reusable-workflows/.github/workflows/auto-merge-branches.yml@main
    with:
      branch: ${{ needs.determine-branch.outputs.branch }}
    secrets:
      BS_GH_PAT: ${{ secrets.BS_GH_PAT }}
